@startuml
!include QAbstractGraphicsShapeItem.puml

class QGraphicsEllipseItem {
  +QGraphicsEllipseItem(QGraphicsItem *parent = nullptr)
}

QAbstractGraphicsShapeItem <|-- QGraphicsEllipseItem
@enduml
