@startuml
!include QAbstractGraphicsShapeItem.puml

class QGraphicsPolygonItem {
  +QGraphicsPolygonItem(QGraphicsItem *parent = nullptr)
}

QAbstractGraphicsShapeItem <|-- QGraphicsPolygonItem
@enduml
